version: '3.8'

services:
  # Backend Express server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./tests:/app/tests
      - ./playwright.config.js:/app/playwright.config.js
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React app served by nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  # E2E tests using Playwright
  e2e-tests:
    image: mcr.microsoft.com/playwright:v1.46.0-jammy
    working_dir: /app
    volumes:
      - ./e2e-tests:/app/tests
      - ./playwright.config.docker.js:/app/playwright.config.js
      - ./e2e-package.json:/app/package.json
    environment:
      - CI=true
      - FRONTEND_URL=http://frontend
      - BACKEND_URL=http://backend:5000
    command: >
      sh -c "
        npm install &&
        sleep 10 &&
        npx playwright test tests/ --reporter=html
      "
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
